CREATE TABLE MEDICATIONS (
  medID VARCHAR2(100) PRIMARY KEY,
  name VARCHAR2(100),
  brand VARCHAR2(100),
  dosage VARCHAR2(100),
  quantity NUMBER,
  expdate DATE,
  supplierID VARCHAR2(100) REFERENCES SUPPLIER(supplierID)
  );

CREATE TABLE PRESCRIPTIONS (
  prescID VARCHAR2(100) PRIMARY KEY,
  patientID VARCHAR2(100) REFERENCES PATIENT(patientID),
  medID VARCHAR2(100) REFERENCES MEDICATIONS(medID),
  physicianID VARCHAR2(100) REFERENCES PHYSICIAN(physicianID),
  prescdate DATE,
  dosage VARCHAR2(100)
);

CREATE TABLE PATIENT (
  patientID VARCHAR2(100) PRIMARY KEY,
  name VARCHAR2(100),
  contactno VARCHAR2(100),
  DOB DATE,
  IC VARCHAR2(100),
  gender CHAR(1)
);

CREATE TABLE PHARMACIST (
  pharmacistID VARCHAR2(100) PRIMARY KEY,
  name VARCHAR2(100),
  contactno VARCHAR2(100),
  email VARCHAR2(100),
  hiredate DATE,
  credentials VARCHAR2(100)
);

CREATE TABLE PHYSICIAN (
  physicianID VARCHAR2(100) PRIMARY KEY,
  name VARCHAR2(100),
  contactno VARCHAR2(100),
  email VARCHAR2(100),
  prescdate DATE
);
